### PR TITLE
update to use simple python logger

### PR DESCRIPTION
**Pull request by shakyav**
update logger to use simple python logger

### CODE REVIEW

**Review by rnetser — CHANGES_REQUESTED** [review]
ocm_python_wrapper/logger.py should be deleted

**Comment by shakyav** [comment]
> ocm_python_wrapper/logger.py should be deleted

deleted existing logger.py

**Review by rnetser — APPROVED** [review]

**Review by myakove — APPROVED** [review]

**Comment by omrirh** [comment]
please rebase; rather than this lgtm

**Review by myakove — APPROVED** [review]

**Pull request merged**
